**PARTE I: ¿Dónde me pongo como el Kiko?**
***
Rafa, Nacho y Clara quieren comprar palmeras, donuts, hojaldres y tartas. Cada uno necesita diferentes cantidades y pueden elegir dos tiendas: Manolo Bakes y Starbucks.

Las siguiente tablas muestran, respectivamente, la cantidad que cada uno necesita, y los precios en cada una de las tiendas

Palmeras	Donuts	Hojaldres	Tartas
Rafa	6	5	3	1
Nacho	3	6	2	2
Clara	3	4	3	1
Manolo Bakes	Starbucks
Palmera	1.50	1.00
Donut	2.00	2.50
Hojaldre	5.00	4.50
Tarta	
1. **SE PIDE**: genera la matriz que exprese la cantidad que cada persona gastaría en cada tienda, y recomienda a cada uno dónde debería hacer sus compras (pista: donde le cueste menos, ¿no?)
2. **REQUISITO**: emplea Numpy, su tipo array y sus operaciones para la resolución del ejercicio.o.rbucks gastaría:


In [13]:
import numpy as np

cantidades = np.array([[6, 5, 3, 1], #las cantidades de cada producto que quiere Rafa
                       [3, 6, 2, 2], #las cantidades de cada producto que quiere Nacho
                       [3, 4, 3, 1]]) #las cantidades de cada producto que quiere Clara

precios = np.array([[1.50, 2.00, 5.00, 16.00], #precios de cada producto de la tienda Manolo Bakes
                    [1.00, 2.50, 4.50, 17.00]]) #precios de cada producto de la tienda Starbucks

#creamos una matriz con el gasto que haria cada persona en cada tienda
gastos = cantidades.dot(precios.T) #transponemos los precios para que coincidan las dimensiones
print(gastos)



[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]


In [29]:
for i in range(len(cantidades)): 
    min_gasto = gastos[i].min() #para saber cual es el gasto minimo de la fila i
    min_indice = gastos[i].argmin() #para saber cual es el índice del gasto minimo de la fila i
    if min_indice == 0: #si el índice es 0, recomendamos la tienda Manolo Bakes
        tienda = "Manolo Bakes"
    else: #si el índice es 1, recomendamos la tienda Starbucks
        tienda = "Starbucks"
        
    print("La persona", i+1, "debería comprar en",tienda, "donde gastaría", min_gasto, "euros.")

La persona 1 debería comprar en Starbucks donde gastaría 49.0 euros.
La persona 2 debería comprar en Manolo Bakes donde gastaría 58.5 euros.
La persona 3 debería comprar en Manolo Bakes donde gastaría 43.5 euros.


**PARTE II: Clasificador de peliculas**
***
**Similitud entre peliculas**: vamos a calcular similitudes entre peliculas. Para ello las clasificamos segun egeneros, en concreto tenemos:
1. *Toy Story:* Aventura, Animacion, Comedia
2. *Jumanji:* Aventura
3. *Mortal Combat:* Accion, Aventura
4. *Pocahontas:* Animacion, Romance
***
Y ahora calcularemos por el metodo del coseno. Para ello:
1. Convierte cada pelicula en un vector y almacenalo en un diccionario con clave el nombre de la pelicula. Pista: para convertirlo en vector, crea un vector/lista por pelicula con esta estructura.
2. Crea una matriz de peliculas con un array de numpy. Muestra la dimension, shape, tamaño y tipo del array.
3. A partir de la similitud por coseno, genera un programa que calcule la similitud entre cada pelicula y nos diga cuales son mas parecidas entre si. sí.énero?):
óó

In [28]:
import numpy as np

#creamos el diccionario peliculas vacío
peliculas = {}
#asignamos valor 1 si pertenece a ese genero y valor 0 si no pertenece
#lista de generos por orden: aventura, animacion, comedia, accion, romance
#añadimos cada película con su vector correspondiente
peliculas["Toy Story"] = np.array([1, 1, 1, 0, 0])
peliculas["Jumanji"] = np.array([1, 0, 0, 0, 0])
peliculas["Mortal Combat"] = np.array([1, 0, 0, 1, 0])
peliculas["Pocahontas"] = np.array([0, 1, 0, 0, 1])
print(peliculas)

#creamos la matriz de películas a partir del diccionario
matriz_peliculas = np.vstack(list(peliculas.values())) #np.vstack muestra verticalmente los vectores de cada pelicula
print(matriz_peliculas)
print("Dimensión de la matriz:", matriz_peliculas.ndim)
print("Numero de filas y de columnas de la matriz:", matriz_peliculas.shape)
print("Tamaño de la matriz:", matriz_peliculas.size)
print("Tipo de la matriz:", matriz_peliculas.dtype)
#nos sale que la matriz tiene 2 dimensiones, 4 filas, 5 columnas, 20 elementos y que son de tipo entero


{'Toy Story': array([1, 1, 1, 0, 0]), 'Jumanji': array([1, 0, 0, 0, 0]), 'Mortal Combat': array([1, 0, 0, 1, 0]), 'Pocahontas': array([0, 1, 0, 0, 1])}
[[1 1 1 0 0]
 [1 0 0 0 0]
 [1 0 0 1 0]
 [0 1 0 0 1]]
Dimensión de la matriz: 2
Numero de filas y de columnas de la matriz: (4, 5)
Tamaño de la matriz: 20
Tipo de la matriz: int32
