**PRACTICA OBLIGATORIA: NUMPY**
***
**PART I: Nuevos alumnos, "nuevo" algoritmo**
***
**Apartado 1.** Como en la práctica obligatoria de la unidad anterior, se han incorporado dos alumnos a la clase de Dena Aidon: Teresa y Udo. Ambos han rellenado el cuestionario de comer y volar, de la siguiente forma:

Teresa: Comer: -2, Volar: -5
Udo: Comer: 0, Volar
1. A partir de la clase de Dena Aidon, dada como una lista de listas o vectores fila, crea un array de Numpy.
2. Añade a Teresa y Udo de dos formas diferentes mediante concatenacionesciones

In [10]:
import numpy as np
alumnos_aidone = [[5, 4],
                  [2, -3],
                  [3, 5],
                  [-5, 4],
                  [0, -1],
                  [3, 2],
                  [-1, 1],
                  [5, -2],
                  [-5, 3],
                  [-5, 1]]
array_aidone = np.array(alumnos_aidone) #creamos el array de numpy a partir de la lista de listas
print("El array inicial es:", array_aidone)

#forma 1 de añadir a Teresa y Udo: con concatenaciones
Teresa = [-2, -5] #añadimos a Teresa
Udo = [0, 4] #añadimos a Udo
array_aidone = np.concatenate((array_aidone, [Teresa], [Udo]), axis=0)
print("Añadimos a Teresa y Udo y el array quedaria asi:", array_aidone)

El array inicial es: [[ 5  4]
 [ 2 -3]
 [ 3  5]
 [-5  4]
 [ 0 -1]
 [ 3  2]
 [-1  1]
 [ 5 -2]
 [-5  3]
 [-5  1]]
Añadimos a Teresa y Udo y el array quedaria asi: [[ 5  4]
 [ 2 -3]
 [ 3  5]
 [-5  4]
 [ 0 -1]
 [ 3  2]
 [-1  1]
 [ 5 -2]
 [-5  3]
 [-5  1]
 [-2 -5]
 [ 0  4]]


In [13]:
import numpy as np
alumnos_aidone = [[5, 4],
                  [2, -3],
                  [3, 5],
                  [-5, 4],
                  [0, -1],
                  [3, 2],
                  [-1, 1],
                  [5, -2],
                  [-5, 3],
                  [-5, 1]]
array_aidone = np.array(alumnos_aidone) #creamos el array de numpy a partir de la lista de listas
print("El array inicial es:", array_aidone)

#forma 2 de añadir a Teresa y Udo: con append
teresa = [-2, -5]
udo = [0, 4]
array_aidone = np.append(array_aidone, [Teresa, Udo])
array_aidone = array_aidone.reshape((6, 4))
print("Añadimos a Teresa y Udo y el array quedaria asi:", array_aidone)

El array inicial es: [[ 5  4]
 [ 2 -3]
 [ 3  5]
 [-5  4]
 [ 0 -1]
 [ 3  2]
 [-1  1]
 [ 5 -2]
 [-5  3]
 [-5  1]]
Añadimos a Teresa y Udo y el array quedaria asi: [[ 5  4  2 -3]
 [ 3  5 -5  4]
 [ 0 -1  3  2]
 [-1  1  5 -2]
 [-5  3 -5  1]
 [-2 -5  0  4]]


**Apartado 2.** Modificar el algoritmo de elección de la clase extraescolar principal (el presentado en la siguiente celda) de forma que:

1. En vez de emplear el diccionario de reparto empleemos una matriz de (12x3) incializada con 0 en todas sus posiciones.
2. Emplee alguna de las funciones de la librería numpy en las líneas señaladas para hacer los cálculos
3. Utilice alguna de las funciones de agregación vistas para obtener la clase extraescolar asignada

In [ ]:
alumnos_ref = ["Rodrigo","Gabriela","Mateo"]
lista_alumnos = ['Rodrigo', 'Lucia', 'Alejandro', 'Valeria', 'Javier', 'Camila', 'Diego', 'Gabriela', 'Mateo', 'Sofía','Teresa','Udo']
curso_asignado = ["CAI","ER","NMPC"]

##### CAMBIA LA SIGUIENTE LINEA, según 2.1 ######
import numpy as np
matriz_reparto = np.zeros((12,3)) #creamos una matriz de 12 filas y 3 columnas con 0s
print(matriz_reparto)

num_alumnos = len(lista_alumnos)

for i_vector in range(num_alumnos): # Recorremos el diccionario donde tenemos el vector que caracteriza 
    
    alumno = lista_alumnos[i_vector]
    vector_alumno = alumnos_aidone[i_vector]
    print("Par", alumno, "con vector", vector_alumno)

    distancia_minima = 99999999 
    indice_distancia_minima = -1

    vector_distancias = np.full((3),1000) # 1000 es un número arbitrario, no le des vueltas a por qué ese número.

    for indice_curso,alumno_ref in enumerate(alumnos_ref):
        indice_alumno_ref = lista_alumnos.index(alumno_ref)
        vec_ref = alumnos_aidone[indice_alumno_ref] 
        
      ####### 2.2 MODIFICA EL SIGUIENTE FRAGMENTO PARA UTILIZAR METODOS Y FuNCIONES NUMPY, recuerda que la norma se obtiene con np.linalg.norm ####
      vector_alumno = alumnos_aidone[i_vector]
      vec_ref = alumnos_aidone[indice_alumno_ref] 
      #convertimos las listas en arrays de numpy
      array1 = np.array(vector_alumno)
      array2 = np.array(vec_ref)
      resultado = array1 - array2
      distancia = np.linalg.norm(resultado) # Calcula la distancia entre dos vectores
        #########################################################################################################################################
        vector_distancias[indice_curso] = distancia  
   
    ######################################################### 2.3 COMPLETA LA SIGUIENTE LINEA ######################################
    indice_curso_asignado = np.argmin(matriz_reparto[i_vector]) # Obtiene el índice del valor mínimo de la fila i_vector
    curso_asignado = curso_asignado[indice_curso_asignado] # Obtiene el nombre del curso asignado
    print(curso_asignado)
    ###############################################################################################

**PARTE II: Mini hundir la flota**
***
1. Crea un tablero de 10x10 relleno del carácter espacio " ". (Utiliza un array de Numpy para representarlo y creálo utilizando las inicializaciones que hemos aprendido)
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X.
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero de manera ALEATORIA.

,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. Ojo con las posiciones donde ya hay barco!!!

Usa import random para elegir las coordenadas aleatorias.

NOTA: Intenta crear fuciones para crear el tablero (de forma que tenga dimensiones variables), posicinar los barcos, generar los disparos dadas unas coordenadas, y generar barcos de forma aleatoria

In [38]:
import numpy as np
tablero = np.full((10, 10), " ") #creamos un array de 10x10 con espacios
tablero[0, 1] = "Y" #posicionamos el primer barco en (0, 1)
tablero[1, 1] = "Y" #posicionamos el primer barco en (1, 1)
tablero[1, 3:7] = "Y" #posicionamos el segundo barco en (1, 3), (1, 4), (1, 5), (1, 6)
print(tablero)
tablero[1, 1] = "X" #recibe un disparo en el primer barco en (1, 1)
print(tablero)
tablero[3, 2] = "A" #recibe un disparo en agua en (2, 2)
print(tablero)
#Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero de manera ALEATORIA.
import random
barco_valido = False #variable que controla si el barco es válido
while not barco_valido: 
    fila = random.choice(range(10)) #elegimos una fila al azar entre 0 y 9
    columna = random.choice(range(10)) #elegimos una columna al azar entre 0 y 9
    orientacion = random.choice(["Norte", "Sur", "Este", "Oeste"]) #elegimos una orientación al azar entre norte, sur, este u oeste
    if orientacion == "Norte": 
        if fila >= 3: #comprobamos si el barco cabe en el tablero
            if np.all(tablero[fila-3:fila+1, columna] == " "): #comprobamos si el barco no se solapa con otro
                tablero[fila-3:fila+1, columna] = "Y" #posicionamos el barco
                barco_valido = True #indica que el barco es válido
    elif orientacion == "Sur": 
        if fila <= 6: #comprobamos si el barco cabe en el tablero
            if np.all(tablero[fila:fila+4, columna] == " "): #comprobamos si el barco no se solapa con otro
                tablero[fila:fila+4, columna] = "Y" #posicionamos el barco
                barco_valido = True #indica que el barco es válido
    elif orientacion == "Este": 
        if columna <= 6: #comprobamos si el barco cabe en el tablero
            if np.all(tablero[fila, columna:columna+4] == " "): #com`robamos si el barco no se solapa con otro
                tablero[fila, columna:columna+4] = "Y" #posicionamos el barco
                barco_valido = True #indica que el barco es válido
    elif orientacion == "Oeste": 
        if columna >= 3: #comprobamos si el barco cabe en el tablero
            if np.all(tablero[fila, columna-3:columna+1] == " "): #comprobamos si el barco no se solapa con otro
                tablero[fila, columna-3:columna+1] = "Y" #posicionamos el barco
                barco_valido = True #indica que el barco es válido
print(tablero)


[[' ' 'Y' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'Y' ' ' 'Y' 'Y' 'Y' 'Y' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
[[' ' 'Y' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' 'Y' 'Y' 'Y' 'Y' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
[[' ' 'Y' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' 'Y' 'Y' 'Y' 'Y' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' '